prepare_data_script: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/1_prepare_data.Rmd"
DESeq2_script: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/2_bulk_RNA_seq_DESeq2.Rmd"
storeData_script: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/3_bulk_RNA_seq_storeData.Rmd"
ShinyInternal_script: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/4_bulk_RNA_seq_ShinyInternal.R"
storshow_functions: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/storshow_functions.R"

count_matrix_fn: "CypKO_counts.tsv"
extra_data_dds: "/data/cabezas/group/pavlovich/data/shared/storshow/extra_data/TwoExp_dds_28s_34787g.rds"

dataDirectory_orig: "/data/cabezas/group/pavlovich/data/shared/storshow/R/versions/20200630_organisms/bulk_CypKO_inVitro_VitA"
samp: "CypKO_inVitro"
organism: "mouse"
rm_samples: ["Ctrl_4oxoRA_142", "Ctrl_DMSO_142", "Ctrl_atRA_142", "Ctrl_retinol_142"]

avg_cond_thr: 100

treat_cond: ["Ctrl_4oxoRA", "KO_4oxoRA", "KO_4oxoRA", "KO_4oxoRA", 
                "Ctrl_atRA", "KO_atRA", "KO_atRA", "KO_atRA", 
                "Ctrl_retinol", "KO_retinol", "KO_retinol", "KO_retinol", 
                "KO_DMSO"]
ctr_cond: ["Ctrl_DMSO", "Ctrl_DMSO", "KO_DMSO", "Ctrl_4oxoRA", 
                "Ctrl_DMSO", "Ctrl_DMSO", "KO_DMSO", "Ctrl_atRA", 
                "Ctrl_DMSO", "Ctrl_DMSO", "KO_DMSO", "Ctrl_retinol", 
                "Ctrl_DMSO"]

betaPrior: "TRUE"
DESeq2_padj_thr: 0.1
DESeq2_absLog2FC_thr: 0
MA_plots_ylim: [-3,3]

ORA_padj_thr: 0.1
maxCores: 20
GSEA_padj_thr: 0.01
gmt.file: "/data/cabezas/group/pavlovich/data/shared/storshow/signatures/Signatures_for_GSEA_updated_20200309.gmt"
avg_pair_overl_thr: 70
levels_ordered: ["Ctrl_DMSO", "Ctrl_4oxoRA", "Ctrl_atRA", "Ctrl_retinol",
                    "KO_DMSO", "KO_4oxoRA", "KO_atRA", "KO_retinol"]

colors_ordered: ["#FB9A99", "#A6CEE3", "#B2DF8A", "#FDBF6F", 
                    "#E31A1C", "#1F78B4", "#33A02C", "#FF7F00"]
titlePage: "Bulk RNA-seq of Ctr and CypKO in vitro treated HSCs"
first_gene_to_show: "Cyp26b1"
first_custom_GSEA_to_show: "clus31_MPPs"
first_allPath_GSEA_to_show: "5991454_M_Phase"
extra_data_comment: "Published sets are used only on this page."

front_target_barplot_height: "auto"
front_target_barplot_width: "auto"
front_extra_barplot_height: "280px"
front_extra_barplot_width: "600px"

showCateg: 25
showCategCnet: 6
maxNgenes: 7
DE_df_height: "400px"
MA_plots_width: "600px"
Volcano_plots_width: "600px"
Volcano_nShow_geneNames: 25
