name: storshow
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python>3
  - snakemake>5.13
  - r=4.0
  - r-biocmanager=1.30.10
  - bioconductor-biomart
  - bioconductor-deseq2
  - r-shiny
  - r-dt
  - bioconductor-summarizedexperiment
  - bioconductor-fgsea
  - r-rcpp
  - r-ggplot2
  - r-kableextra
  - bioconductor-enrichplot
  - bioconductor-singlecellexperiment
  - r-ggpubr
  - r-venndiagram
  - r-data.table
  - bioconductor-biocgenerics
  - r-bitops
  - bioconductor-biobase
  - r-png
  - r-gridextra
  - r-htmlwidgets
  - r-tidyselect
  - r-purrr
  - r-cowplot
  - r-igraph
  - r-tidyr
  - r-ggrepel
  - r-reshape2
  - r-plyr
  - r-ggridges
  - r-curl
  - r-gdata
  - r-gtools
  - bioconductor-org.mm.eg.db
  - bioconductor-org.hs.eg.db
  - bioconductor-clusterprofiler
  - r-pheatmap
  - r-doparallel
  - r-foreach
  - r-dbscan
